import NavBar from "@/components/client/common/NavBar";
import NavbarContainer from "@/components/server/config/NavbarContainer";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Provider>
          <NavbarContainer>
            <NavBar />
          </NavbarContainer>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
