import NavBar from "@/components/client/common/NavBar";
import NavbarContainer from "@/components/server/config/NavbarContainer";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <NavbarContainer>
          <NavBar />
        </NavbarContainer>
        {children}
      </body>
    </html>
  );
}
